data = {
   adjectives: [
      "Amazing",
      "Ancient",
      "Award-winning",
      "Backwards",
      "Bad",
      "Battery-Powered",
      "Beautiful",
      "Bored",
      "Boring",
      "Bouncing",
      "Chilly",
      "Chocolate",
      "Clockwork",
      "Creepy",
      "Dancing",
      "Desperate",
      "Disappearing",
      "Dizzy",
      "Double",
      "Dusty",
      "Electric",
      "Enchanted",
      "Exploding",
      "Expensive",
      "Fake",
      "Famous",
      "Floating",
      "Forgotten",
      "Flying",
      "Frozen",
      "Furry",
      "Fussy",
      "Fuzzy",
      "Ghost",
      "Giddy",
      "Gigantic",
      "Giggling",
      "Golden",
      "Greedy",
      "Green",
      "Hairy",
      "Hard-working",
      "Haunted",
      "Heavy",
      "Hidden",
      "Hissing",
      "Howling",
      "Hungry",
      "Incredible",
      "Imaginary",
      "Intergalactic",
      "Invisible",
      "Jumbo",
      "Jumping",
      "Kung-Fu",
      "Lazy",
      "Leaping",
      "Lucky",
      "Magic",
      "Martian",
      "Messy",
      "Midnight",
      "Miniature",
      "Missing",
      "Mouldy",
      "Multi-coloured",
      "Musical",
      "Mysterious",
      "Nightmare",
      "Noisy",
      "Old-fashioned",
      "Orange",
      "Outer-Space",
      "Pet",
      "Phantom",
      "Plastic",
      "Posh",
      "Prehistoric",
      "Prize-winning",
      "Revolting",
      "Royal",
      "Rubber",
      "Seaside",
      "Scary",
      "Secret",
      "Shining",
      "Shrinking",
      "Silent",
      "Silly",
      "Silver",
      "Singing",
      "Slippery",
      "Smelly",
      "Speedy",
      "Spooky",
      "Sticky",
      "Stinky",
      "Stolen",
      "Stormy",
      "Super",
      "Terrible",
      "Ticklish",
      "Tiny",
      "Undercover",
      "Underwater",
      "Unexpected",
      "Unlucky",
      "Unstoppable",
      "Upside-down",
      "Vampire",
      "Whistling",
      "Windy",
      "Wobbly",
      "Wonky",
      "Wooden",
      "Woolly",
      "World's Biggest",
      "World's Worst"
   ],

   nouns: [
      "Alien",
      "Apple",
      "Ant",
      "Astronaut",
      "Banana",
      "Beetle",
      "Bicycle",
      "Birthday",
      "Biscuit",
      "Bookcase",
      "Boots",
      "Breakfast",
      "Bus",
      "Cake",
      "Candle",
      "Cat",
      "Cheese",
      "Chicken",
      "Circus",
      "Classroom",
      "Clock",
      "Clown",
      "Computer",
      "Cottage",
      "Crab",
      "Crow",
      "Dentist",
      "Diary",
      "Dice",
      "Dinosaur",
      "Dinner",
      "Donkey",
      "Donut",
      "Dragon",
      "Drum",
      "Drummer",
      "Duck",
      "Dungeon",
      "Egg",
      "Elephant",
      "Fairy",
      "Feet",
      "Fingers",
      "Fish",
      "Flute",
      "Forest",
      "Fortress",
      "Frog",
      "Garden",
      "Gerbil",
      "Giant",
      "Gloves",
      "Goat",
      "Goblin",
      "Goldfish",
      "Gremlin",
      "Haircut",
      "Helicopter",
      "Holiday",
      "Island",
      "Jellyfish",
      "Jigsaw",
      "Kangaroo",
      "Kingdom",
      "Kitchen",
      "Kitten",
      "Library",
      "Lobster",
      "Lunchbox",
      "Milkshake",
      "Monkey",
      "Monster",
      "Mountain",
      "Mouse",
      "Nose",
      "Octopus",
      "Owl",
      "Paintbrush",
      "Panda",
      "Party",
      "Pencil",
      "Piano",
      "Pizza",
      "Penguin",
      "Pencil case",
      "Planet",
      "Potato",
      "Pudding",
      "Pumpkin",
      "Puppy",
      "Rabbit",
      "Radio",
      "Rainbow",
      "Robot",
      "Roses",
      "Sandwich",
      "School",
      "Scooter",
      "Shark",
      "Sheep",
      "Shoes",
      "Skateboard",
      "Skeleton",
      "Slippers",
      "Socks",
      "Spider",
      "Submarine",
      "Teacher",
      "Teapot",
      "Teddy",
      "Tiger",
      "Treasure",
      "Trombone",
      "Trousers",
      "Trumpet",
      "Turtle",
      "TV",
      "Whale",
      "Witch",
      "Wizard",
      "Wolf",
      "Worm",
      "Zoo"
   ],

   classics: [
      {
         quote: "The Mole had been working very hard all the morning, spring-cleaning his little home.",
         book: "The Wind in the Willows",
         author: "Kenneth Grahame",
         link: "https://en.wikisource.org/wiki/The_Wind_in_the_Willows_(1908)"
      },
      {
         quote: "In a hole in the ground there lived a hobbit.",
         book: "The Hobbit",
         author: "J.R.R. Tokein",
         link: "https://en.wikipedia.org/wiki/The_Hobbit"
      },
      {
         quote: "Miss Cackle's Academy for Witches stood at the top of a high mountain surrounded by a pine forest.",
         author: "Jill Murphy",
         book: "The Worst Witch",
         link: "https://en.wikipedia.org/wiki/The_Worst_Witch"
      },
      {
         quote: "If you went too near the edge of the chalk-pit the ground would give way. Barney had been told this often enough.",
         author: "Clive King",
         book: "Stig of the Dump",
         link: "https://www.booktrust.org.uk/book/s/stig-of-the-dump/"
      },
      {
         quote: "'Christmas won't be Christmas without any presents,' grumbled Jo, lying on the rug.",
         author: "Louisa May Alcott",
         book: "Little Women",
         link: "https://en.wikisource.org/wiki/Little_Women"
      },
      {
         quote: "This is how the story begins. On a dark, dark hill, there was a dark, dark town.",
         author: "Janet &amp; Allan Ahlberg",
         book: "Funnybones",
         link: "https://www.goodreads.com/book/show/1208469.Funnybones"
      },
      {
         quote: "Mr and Mrs Dursley, of number four Privet Drive, were proud to say that they were perfectly normal, thank you very much.",
         author: "J.K. Rowling",
         book: "Harry Potter and the Philosopher's Stone",
         link: "https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone"
      },
      {
         quote: "Down in the valley there were three farms. The owners of these farms had done well. They were rich men. They were also nasty men. All three of them were about as nasty and mean as any men you could meet. Their names were Farmer Boggis, Farmer Bunce and Farmer Bean.",
         author: "Roald Dahl",
         book: "Fantastic Mr. Fox",
         link: "https://www.roalddahl.com/roald-dahl/stories/f-j/fantastic-mr-fox"
      },
      {
         quote: "The Iron Man came to the top of the cliff. How far had he walked? Nobody knows. Where had he come from? Nobody knows.",
         author: "Ted Hughes",
         book: "The Iron Man",
         link: "https://www.bl.uk/collection-items/the-iron-man-by-ted-hughes"
      },
      {
         quote: "Once there was a little girl called Sophie. She was having tea with her mummy in the kitchen. Suddenly there was a ring at the door. Sophie’s mummy said 'I wonder who that could be?'",
         author: "Judith Kerr",
         book: "The Tiger Who Came to Tea",
         link: "https://www.bl.uk/collection-items/the-tiger-who-came-to-tea-by-judith-kerr-sketches-and-original-artwork"
      },
      {
         quote: "In an old house in Paris that was covered with vines<br>Lived twelve little girls in two straight lines.<br>They left the house at half past nine...<br>The smallest one was Madeline.",
         author: "Ludwig Bemelmans",
         book: "Madeline",
         link: "http://www.madeline.com/history.html"
      },
      {
         quote: "My name is Tracy Beaker. I am 10 years 2 months old. My birthday is on May 8. It's not fair, because that dopey Peter Ingham has his birthday then too, so we just got the one cake between us.",
         author: "Jacqueline Wilson",
         book: "The Story of Tracy Beaker",
         link: "https://www.booktrust.org.uk/book/t/the-story-of-tracy-beaker/"
      },
      {
         quote: "There was a boy called Eustace Clarence Scrubb, and he almost deserved it.",
         author: "C.S. Lewis",
         book: "The Voyage of the Dawn Treader",
         link: "https://en.wikipedia.org/wiki/The_Voyage_of_the_Dawn_Treader"
      },
      {
         quote: "Once upon a time there lived... 'A king!' my little readers will say immediately. No, children, you are mistaken. Once upon a time there was a piece of wood.",
         author: "Carlo Collodi",
         book: "The Adventures of Pinocchio",
         link: "https://www.booktrust.org.uk/book/t/the-adventures-of-pinocchio/"
      },
      {
         quote: "I write this sitting in the kitchen sink.",
         author: "Dodie Smith",
         book: "I Capture the Castle",
         link: "https://www.booktrust.org.uk/book/i/i-capture-the-castle/"
      },
      {
         quote: "Once upon a time there was a huge family of children; and they were terribly, terribly naughty.",
         author: "Christianna Brand",
         book: "Nurse Matilda",
         link: "https://en.wikipedia.org/wiki/Nurse_Matilda"
      },
      {
         quote: "It was Monday morning, it was pouring with rain, and it was everyone's first day back at St Barty's Primary School after the Christmas holidays.",
         author: "Humphrey Carpenter",
         book: "Mr. Majeika",
         link: "https://en.wikipedia.org/wiki/Mr_Majeika"
      },
      {
         quote: "The swirling rain-clouds rushed on revealing the bright moon, and the two Borribles dodged behind the bushes and kept as quiet as they could. There was danger in the air and they could feel it. It would pay to be cautious.",
         author: "Michael de Larrabeiti",
         book: "The Borribles",
         link: "https://en.wikipedia.org/wiki/The_Borrible_Trilogy"
      },
      {
         quote: "All children, except one, grow up.",
         author: "J.M. Barrie",
         book: "Peter Pan",
         link: "https://en.wikisource.org/wiki/Peter_and_Wendy_(1911)"
      },
      {
         quote: "Sophie couldn’t sleep. A brilliant moonbeam was slanting through a gap in the curtains. It was shining right on her pillow.",
         author: "Roald Dahl",
         book: "The BFG",
         link: "https://www.roalddahl.com/roald-dahl/stories/a-e/the-bfg"
      },
      {
         quote: "Look, I didn’t want to be a half-blood.",
         author: "Rick Riordan",
         book: "Percy Jackson and the Lightning Thief",
         link: "https://www.booktrust.org.uk/book/p/percy-jackson-and-the-lightning-thief/"
      },
      {
         quote: "Until he was four years old, James Henry Trotter had a happy life.",
         author: "Roald Dahl",
         book: "James and the Giant Peach",
         link: "https://www.roalddahl.com/roald-dahl/stories/f-j/james-and-the-giant-peach"
      }
   ]
}